name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          if grep version pyproject.toml | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter/archive/main.zip;
          fi
      - uses: pre-commit/action@v3.0.1
